title: Keyao's Coding Blog
author: "Keyao Zhan"
description: "A blog about software development, coding challenges, and technical discoveries"
baseurl: "/mypage"
url: "https://kyzhan2002.github.io"

social:
  github: keyaozhan

plugins:
  - jekyll-seo-tag

sass:
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown
theme: minima

permalink: /:categories/:title/

defaults:
  - scope:
      path: "blog"
      type: "pages"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  blog:
    output: true
    permalink: /blog/:title
