name: Update arXiv Papers

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:      # Allow manual triggers
  repository_dispatch:    # Add this trigger
    types: [refresh-papers]

permissions:
  contents: write

jobs:
  update-papers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Create data directory
        run: mkdir -p _data
          
      - name: Fetch papers
        run: python _scripts/fetch_papers.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --cached --quiet || (git commit -m "Update arXiv papers" && git push)