name: Update arXiv Papers

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:      # Allow manual triggers

permissions:
  contents: write

jobs:
  update-papers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install dependencies
        run: |
          bundle install

      - name: Create data directory
        run: mkdir -p _data
          
      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace
        
      - name: Debug file contents
        run: |
          echo "Checking _data directory:"
          ls -la _data
          if [ -f "_data/arxiv_cache.json" ]; then
            echo "Cache file contents:"
            cat "_data/arxiv_cache.json"
          fi
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --cached --quiet || (git commit -m "Update arXiv papers" && git push)