name: Update arXiv Papers

on:
  schedule:
    - cron: '0 */24 * * *'  # Run every 24 hours
  workflow_dispatch:      # Allow manual triggers

permissions:
  contents: write

jobs:
  update-papers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Create data directory
        run: mkdir -p _data
          
      - name: Fetch papers
        run: python _scripts/fetch_papers.py
        
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --cached --quiet || (git commit -m "Update arXiv papers" && git push)